version: 0.0
os: linux
files:
  - source: /
    destination: /deploy
hooks:
  ApplicationStop:
    - location: infrastructure/aws/codedeploy/stop_server
      timeout: 300
      runas: root
  BeforeInstall:
    - location: infrastructure/aws/codedeploy/install_dependencies
      timeout: 300
      runas: root
  AfterInstall:
    - location: infrastructure/aws/codedeploy/after_install
      timeout: 300
      runas: root
  ApplicationStart:
    - location: infrastructure/aws/codedeploy/start_server
      timeout: 300
      runas: root
  ValidateService:
    - location: infrastructure/aws/codedeploy/validate_service
      timeout: 300
      runas: root
